export const mockData = [
  {
    id: 1,
    name: {
      first: "David",
      last: "Broski",
    },
    email: "david.broski@example.com",
    createdAt: "2024-12-01",
    nationality: "USA",
    createdJobs: 12,
    appliedJobs: 5,
  },
  {
    id: 2,
    name: {
      first: "Maggie",
      last: "Nguyen",
    },
    email: "maggie.nguyen@example.com",
    createdAt: "2024-11-21",
    nationality: "Vietnam",
    createdJobs: 4,
    appliedJobs: 9,
  },
  {
    id: 3,
    name: {
      first: "Gabriel",
      last: "Gonzalez",
    },
    email: "gabriel.gonzalez@example.com",
    createdAt: "2024-10-03",
    nationality: "Mexico",
    createdJobs: 7,
    appliedJobs: 12,
  },
  {
    id: 4,
    name: {
      first: "Samantha",
      last: "Lee",
    },
    email: "samantha.lee@example.com",
    createdAt: "2024-08-15",
    nationality: "Canada",
    createdJobs: 3,
    appliedJobs: 2,
  },
  {
    id: 5,
    name: {
      first: "Daniel",
      last: "Chen",
    },
    email: "daniel.chen@example.com",
    createdAt: "2024-07-30",
    nationality: "Taiwan",
    createdJobs: 11,
    appliedJobs: 7,
  },
  {
    id: 6,
    name: {
      first: "Avery",
      last: "Williams",
    },
    email: "avery.williams@example.com",
    createdAt: "2024-09-11",
    nationality: "UK",
    createdJobs: 6,
    appliedJobs: 3,
  },
  {
    id: 7,
    name: {
      first: "Oliver",
      last: "Martinez",
    },
    email: "oliver.martinez@example.com",
    createdAt: "2024-06-22",
    nationality: "Spain",
    createdJobs: 2,
    appliedJobs: 14,
  },
  {
    id: 8,
    name: {
      first: "Sophia",
      last: "Garcia",
    },
    email: "sophia.garcia@example.com",
    createdAt: "2024-12-05",
    nationality: "Argentina",
    createdJobs: 0,
    appliedJobs: 8,
  },
  {
    id: 9,
    name: {
      first: "Jacob",
      last: "Liu",
    },
    email: "jacob.liu@example.com",
    createdAt: "2024-11-10",
    nationality: "Singapore",
    createdJobs: 5,
    appliedJobs: 10,
  },
  {
    id: 10,
    name: {
      first: "Isabella",
      last: "Wong",
    },
    email: "isabella.wong@example.com",
    createdAt: "2024-10-18",
    nationality: "Malaysia",
    createdJobs: 8,
    appliedJobs: 6,
  },
];
